### ISSUE TITLE
.send_request doesn't check the status of the response

### ISSUE THREAD

**Issue by MarcinKosinski** [szymanskir/hackeRnews#34]
There might be the case that the response returned by `httr::GET(url = request_url)` in `.send_request` returns a `status` different than `200`. There should be an if statement checking that the response returned the status equal to 200 and if not, then the execution should be stopped.

**Comment by szymanskir** [comment]
Actually the http status is checked by the `validate_hn_api_response` function :smile:

If a situation where an error response is received occurs, the content of the response is retrieved and used as a message when generating an error via `stop`. Providing an example below:

``` r
hackeRnews:::.send_request(request_url = "https://hacker-news.firebaseio.com/v0/non_existing_endpoint_for_error_response_example.json")
#> Error: The request resulted with an error [401]
#> Permission denied
#> <https://hacker-news.firebaseio.com/v0/non_existing_endpoint_for_error_response_example.json>
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MarcinKosinski** [comment]
Wow, sorry, haven't seen this one. Great to know
